### ISSUE TITLE
Add version no in setup.py

### ISSUE THREAD

**Issue by Haiz14** [Haiz14/cmake#2]
The function that finds version in setup.py creates very bad version no like `cmake 0.post2+g292abae `.

So add a version fix version no.

**Comment by laoyur** [comment]
```
$ mv cmake-0.post2+g292abae-cp310-cp310-linux_aarch64.whl cmake-3.22.4-py2.py3-none-any.whl
$ pip install opencv-python --find-links ~/wheels --verbose

...
Processing ./cmake-3.22.4-py2.py3-none-any.whl
  Discarding file:///data/data/com.termux/files/home/wheels/cmake-3.22.4-py2.py3-none-any.whl: Requested cmake from file:///data/data/com.termux/files/home/wheels/cmake-3.22.4-py2.py3-none-any.whl has inconsistent version: filename has '3.22.4', but metadata has '0.post2+g292abae'
  Collecting cmake
    Using cached cmake-3.22.4.tar.gz (31 kB)
    Installing build dependencies: started
```

Hello, how to change version number to `3.22.4`? or can I change it directly in whl file?

**Comment by Haiz14** [comment]
Go to setup.py u will se a version variable, just change it.

**Comment by laoyur** [comment]
@Haiz14 thanks, I already did that, it seems whl file is used by pip now. but `get_cmake_version` raises Error:

```
$ pip install opencv-python --find-links ~/wheels
...
  × Building wheel for opencv-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/bin/cmake", line 8, in <module>
          sys.exit(cmake())
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/cmake/__init__.py", line 47, in cmake
          raise SystemExit(_program('cmake', sys.argv[1:]))
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/cmake/__init__.py", line 43, in _program
          return subprocess.call([os.path.join(CMAKE_BIN_DIR, name)] + args)
        File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 345, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 966, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 1840, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      OSError: [Errno 8] Exec format error: '/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake'
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 141, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-iy7q7879/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
          raise SKBuildError(
      Traceback (most recent call last):
```
version problem?
